Sidepro/Controllers/ModuleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sidepro.Application;
using Sidepro.ViewModels;
using Sidepro.Entities;
using Sidepro.Application.Helpers;
namespace Sidepro.Controllers
{
    public class ModuleController : Controller
    {

        ModuleCursosViewModelController moduleVieweModelController = new ModuleCursosViewModelController();

        public ActionResult Module(int? id_module, int? id_curso)
        {
            ViewBag.Message = "Página de Modulos";
            int id_usuario = obtenerUsuario();
            return View(moduleVieweModelController.getCursosViewModel((int)id_module, id_curso, id_usuario));
        }
        public int obtenerUsuario()
        {
            HttpCookie myCookie = Request.Cookies["UserSettings"];
            int id_usuario = HelpersManagementService.getCookie(myCookie).ID_Usuario;
            /*
            int id_usuario = -1;
            if (HttpContext.Session["IDUsuario"] != null)
            {
                id_usuario = (int)HttpContext.Session["IDUsuario"];
            }
            else
            {
                id_usuario = new indexViewModel().id_usuario;
            }
             */ 
            return id_usuario;
        }
        public ActionResult DescargarNoticia(int id_modulo, int id_curso)
        {

            int cod_usuario = obtenerUsuario();
            Noticia miNoticia = new NoticiaManagementService().GetNoticia(id_modulo, id_curso, cod_usuario);
            string filename = miNoticia.FileName;// "File1.pdf";
            string filepath = AppDomain.CurrentDomain.BaseDirectory + miNoticia.Path;// "/Images/Noticias/" + filename;
            byte[] filedata = System.IO.File.ReadAllBytes(filepath);
            string contentType = MimeMapping.GetMimeMapping(filepath);

            var cd = new System.Net.Mime.ContentDisposition
            {
                FileName = filename,
                Inline = true,
            };

            Response.AppendHeader("Content-Disposition", cd.ToString());

            return File(filedata, contentType);
        }

    }
}

Sidepro/Views/Module/Module.cshtml
@model Sidepro.ViewModels.ModuleCursosViewModel
@using Sidepro.HelperExtensionNameSpace
@using Sidepro.Entities
@{
    ViewBag.Title = "Sidepro Movistar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script>
    $(document).ready(function () {
        $('#divWrapper').addClass("site-content__wrapper--module");

    })
</script>
<div class="module">
    <h1 class="module__title"> @Model.nombreModulo </h1>
</div>

<div class="module__grid js-module-grid">

    @foreach (Curso curso in Model.moduleCourses)
    {

        <div class="module__course">
            @if (curso.Sn_Activo == -2)
            {
                @Html.Raw("<div class='course course--module-featured js-course-hover'>")
            }
            else
            {
                @Html.Raw("<div class='course course--module js-course-hover'>")
            }
            @*<a href="course.html" class="course__pic" style="background-image: url(@curso.URLImagen)"></a>*@
            @if (curso.PuedeRealizar == -1) { 
                @Ajax.RawActionLink("", curso.View, curso.Controller, new { id_module = curso.Id_modulo, id_curso = curso.Id_curso }, null, new { @class = curso.Style, style = "background-image: url(" + ((curso.Id_modulo == 6 && curso.Controller == "Course") ? "../Images/Placeholders/examen.png" : (curso.Controller == "Download" ? "../Images/Placeholders/Word.png" : curso.URLImagen.ToString())) + ")" })
            }
            else
            {
                <a class="course__pic" data-ajax="true" href="javascript:void(0)" style="background-image: url( @( ((curso.Id_modulo == 6 && curso.Controller == "Course") ? "../Images/Placeholders/examen.png" : (curso.Controller == "Download" ? "../Images/Placeholders/Word.png" : curso.URLImagen.ToString()))) )"></a>
            }
            <div class="course__overlay course__overlay--compact course__overlay--alt">
                @*<h2 class="course__title">Samsung Galaxy S6</h2>*@
                <h2 class="course__title">@curso.Nombre </h2>
                @*<p class="course__description js-course-description-ellipsis">Cámara, características generales, diseño y pantalla, seguridad, tips para el vendedor...</p>*@
                <p class="course__description js-course-description-ellipsis">@curso.Descripcion </p>
                <div class="course__btn-container js-course-btn-container">
                    @*<a href="course.html" class="course__btn">Ir al curso<i></i></a>*@
                    @if (curso.Controller == "Download")
                    {
                        @Html.ActionLink("Descargar", "DescargarNoticia", "Module", new { id_modulo = curso.Id_modulo, id_curso = curso.Id_curso }, new { @class = "course__btn", hidefocus = "hidefocus", target = "_blank" })
                    }
                    else
                    {
                        
                        if (curso.PuedeRealizar == -1) { 
                            @Ajax.RawActionLink(((curso.Controller == "Module") ? (curso.Id_modulo != 6 ? "Ver los cursos" : "Ver agenda") : (curso.Id_modulo != 6 ? "Ir al curso" : "ir a examen")) + "<i></i>", curso.View, curso.Controller, new { id_module = curso.Id_modulo, id_curso = curso.Id_curso }, null, new { @class = "course__btn", hidefocus = "hidefocus" })
                        }
                        else
                        {
                            <a class="course__btn" data-ajax="true" hidefocus="hidefocus" href="javascript:void()">Debe finalizar otros cursos primero<i></i></a>
                        }
                    }
                    @*@Ajax.RawActionLink( ((curso.Controller == "Module") ? "Ver los cursos" : "Ir al curso") +"<i></i>", curso.View, curso.Controller, new { id_module = curso.Id_modulo, id_curso = curso.Id_curso }, null, new { @class = "course__btn", hidefocus = "hidefocus" })*@
                </div>
            </div>
            @Html.Raw("</div>")
        </div>


    }
</div>