Sidepro/Controllers/CertificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Sidepro.ViewModels;
using System.Web.Script.Serialization;
using Sidepro.Application;
using Sidepro.Entities;
using Sidepro.Application.Helpers;
namespace Sidepro.Controllers
{
    public class CertificationController : Controller
    {
        LeccionManagementService leccionManagementService = new LeccionManagementService();
        CursosViewModelController cursosVieweModelController = new CursosViewModelController();
        indexViewModel IndexViewModel = new indexViewModel();
        public ActionResult Certification()
        {
            ViewBag.Message = "Página inicial";
            return View(IndexViewModel);//cursosVieweModelController.getCursosViewModel(1, 1));
        }
        public ActionResult obtenerQuiz()
        {

            int id_usuario = obtenerUsuario();
            var json = new JavaScriptSerializer().Serialize(leccionManagementService.getQuizCertificaciones(id_usuario));
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public ActionResult grabarResultado()
        {

            int id_usuario = obtenerUsuario();
            //bool result = leccionManagementService.grabarResultado(4, 0, 0, nota, id_usuario);
            Certification result = leccionManagementService.getResultado(4, 0, 0, id_usuario);
            return Json(new { notaFinal = result.Nota, aprobado = result.Aprobado }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult grabarRespuesta(int question, int answer) {

            int id_usuario = obtenerUsuario();
            leccionManagementService.grabarRespuesta(id_usuario, question, answer);
            return Json(new { result = true }, JsonRequestBehavior.AllowGet);
        
        }
        public int obtenerUsuario()
        {
            HttpCookie myCookie = Request.Cookies["UserSettings"];
            int id_usuario = HelpersManagementService.getCookie(myCookie).ID_Usuario;
            /*
            int id_usuario = -1;
            if (HttpContext.Session["IDUsuario"] != null)
            {
                id_usuario = (int)HttpContext.Session["IDUsuario"];
            }
            else
            {
                id_usuario = new indexViewModel().id_usuario;
            }
            */
            return id_usuario;
        }

        

    }
}

Sidepro/Views/Certification/Certification.cshtml
@model Sidepro.ViewModels.indexViewModel
@using Sidepro.Entities
@using Sidepro.HelperExtensionNameSpace
@{
    ViewBag.Title = "Sidepro Movistar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="../Scripts/projekktor-1.3.09.min.js"></script>
<script src="../Scripts/slickQuiz.js"></script>
<script>
    var urlQuiz = '@Url.Action("ObtenerQuiz", "Certification")';
    var urlSaveQuiz = '@Url.Action("grabarResultado", "Certification")';
    var urlSaveAnswer = '@Url.Action("grabarRespuesta", "Certification")';
    var quizJSON = '';
    var quizHeader = '';
    var aprobo = false;
    var setearQuiz = true;
    var esCertificacion = true;
    var notaFinal = 0;

    $(document).ready(function () {
        // Se esconden y se muestran algunas cosas cuando
        // arranca el quiz con el botón "¡Estoy listo!"
        obtenerQuiz();
        if (setearQuiz){
            var startQuiz = function () {
                $('.js-quiz-tip, .js-quiz-buttons').fadeOut(300, function () {
                    $('.js-quiz-container').css('padding', 0);
                });
                $('.js-quiz-header').slideUp(600, function () {
                    $('.js-quiz-timer').fadeIn(600);
                });
            }
            var finishQuiz = function (results) {
                // Ajustar a cantidad de preguntas necesarias para aprobar la certificación
                /*
                var nota = 0;
                var answer = 0;
                for (i = 0; i < results.questionCount; i++) {
                    if ($('#question' + i).hasClass('correctResponse')) {
                        nota = parseFloat(nota) + parseFloat($('#question' + i).attr('valor'));
                    }

                    for (j = 0; j < $('#question' + i + ' .answers .correct').size() + $('#question' + i + ' .answers .incorrect').size() ; j++) {
                        if ($('#js-quiz_question0_1').is(':checked')) {
                            answer = j;
                            break;
                        }
                    }
                    //saveAnswer(i, answer);

                }
                */
                //saveQuiz(nota);
                saveQuiz();
                //if (results.questionCount == results.score) {
                if (aprobo){
                    var success = 'Aprobaste el test obteniendo un resultado del ' + notaFinal + '% de las preguntas correctas.';// + results.questionCount + ' preguntas.';

                    $('.js-certif-results-title').text('¡Felicitaciones!').addClass('certif-results__title--success');
                    $('.js-certif-results-copy').text(success);
                } else {
                    setTimeout(function () {
                        $('.js-quiz-container').addClass('quiz__container--error');
                    }, 500);

                    var failure = 'Reprobaste el test, ya que respondiste obtuviste solo el ' + notaFinal + '% de las preguntas correctas.'; // ' + results.questionCount + ' results.score

                    $('.js-certif-results-title').text('¡Lo sentimos!').addClass('certif-results__title--failure');
                    $('.js-certif-results-copy').text(failure);
                }
            }

            $("#js-quiz").slickQuiz({
                // Así se pasarían dinámicamente las preguntas precargadas por AJAX...
                // json: url,
                preventUnanswered: true,
                disableRanking: true,
                displayQuestionNumber: false,
                displayQuestionCount: true,
                preventUnansweredText: 'Debes seleccionar una respuesta.',
                checkAnswerText: 'Verificar respuesta',
                nextQuestionText: 'Siguiente &raquo;',
                completeQuizText: 'Finalizar',
                events: {
                    onStartQuiz: startQuiz,
                    onCompleteQuiz: finishQuiz
                }
            });
        }
        function saveQuiz(Nota) {

            $.ajax({
                type: "GET",
                dataType: "json",
                url: urlSaveQuiz,
                contentType: "application/json; charset=utf-8",
                async: false,
                //data: { nota: Nota },
                success: function (data) {
                    
                    aprobo = data.aprobado;
                    notaFinal = data.notaFinal;
                },
                error: function (xhr, status, error) {
                    alert(error);
                }
            });
        }
        function saveAnswer(question, answer) {

            $.ajax({
                type: "GET",
                dataType: "json",
                url: urlSaveQuiz,
                contentType: "application/json; charset=utf-8",
                async: false,
                data: { Question: question, Answer: answer},
                success: function (data) {
                    return data;
                },
                error: function (xhr, status, error) {
                    alert(error);
                }
            });

        }
        function cambiarQuiz(obj) {
            quizJSON = obj;
            quizHeader = quizJSON.info.name;
        }
        function obtenerQuiz() {

                $.ajax({
                    type: "GET",
                    dataType: "json",
                    url: urlQuiz,
                    contentType: "application/json; charset=utf-8",
                    async: false,
                    //data: { id_modulo: idModulo, id_curso: idCurso, id_leccion: idLeccion },
                    success: function (data) {
                        var obj = JSON.parse(data);
                        
                        var yaAprobado = obj.aprobado;
                        if (yaAprobado) {
                            setearQuiz = !yaAprobado;
                            $('#quizDiv').html('Test ya realizado, debe esperar hasta el próximo mes.');
                        } else {
                            if (quizJSON.sn_inicial){
                                if (obj.questions.length < 30) {
                                    $('#btnComenzar').text('CONTINUAR LA PRUEBA');
                                }
                            } else {
                                $('.quiz__header-title').text('Test de @(DateTime.Now.ToString("MMMM", new System.Globalization.CultureInfo("es-AR")))');
                                if (obj.questions.length < 15) {
                                    $('#btnComenzar').text('CONTINUAR LA PRUEBA');
                                }
                            }
                            cambiarQuiz(obj);
                        }
                    },
                    error: function (xhr, status, error) {
                        alert(error);
                    }
                });
        }

    });
</script>


    <div class="quiz quiz--certif" id="js-quiz">
        <div class="quiz__header quiz__header--certif js-quiz-header">
            <p class="quiz__header-subtitle">Certificación</p>
            <h2 class="quiz__header-title quiz__header-title--certif">Test inicial</h2>
        </div>
        <div id="quizDiv" class="quiz__container quiz__container--certif js-quiz-container">
            <div  class="quiz__buttons js-quiz-buttons">
                <button class="quiz__btn quiz__btn--main-certif startQuiz" id="btnComenzar">Comenzar prueba</button>
            </div>

            <div class="quiz__questions" id="js-quiz-questions">
                <div class="quizArea">
                    <div class="quizHeader">
                        <div class="quiz__tip quiz__tip--certif js-quiz-tip">
                            <i></i>
                            
                            
                            
                            <p>Demostrá tus conocimientos, certificate y sé parte de la comunidad de vendedores profesionales.</p>
                        </div>
                    </div>
                </div>
                <div class="quizResults">
                    <div class="certif-results js-certif-results">
                        <h3 class="certif-results__title js-certif-results-title"></h3>
                        <p class="certif-results__copy js-certif-results-copy"></p>
                    </div>
                </div>
            </div>
        </div>
    </div>


 